name: flutter_easy_downloader_lib
description: A library for flutter that provides an easy to use interface for downloading files to your device.
version: 0.0.1
homepage: https://mubashar.dev
repository: https://github.com/MicroProgramer/flutter_easy_downloader_lib.git

environment:
  sdk: ">=3.4.0 <5.0.0"
  flutter: ">=1.17.0"

dependencies:
  isar_flutter_libs: ^3.1.0+1
  flutter_local_notifications: ^17.2.2
  easy_downloader: ^0.0.30
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
